name: Unicus
version: 1.0
description: >
  Glaciem server plugin
author: Tritania
website: https://github.com/tritania/Unicus

main: org.tritania.unicus.Unicus

commands:
  purge:
    description: Purges multihomes
    aliases: []
    usage: /<command> [playername]
  unpurge:
    description: removes the purges of multihomes
    aliases: []
    usage: /<command> [playername]
  plist:
    description: list all purged players
    aliases: []
    usage: /<command>
