name: Unicus
version: 1.0
description: >
  Glaciem server plugin
author: Tritania
website: https://github.com/tritania/Unicus

main: org.tritania.unicus.Unicus

commands:
  nether:
    description: teleports to the nether
    aliases: []
    usage: /<command> [spawn]
  resource:
    description: teleports to the resource map
    aliases: []
    usage: /<command> [spawn]
  unicus:
    description: admin commands
    aliases: []
    usage: /<command> [resource]


