name: Unicus
version: 1.0
description: >
  Glaciem server plugin
author: Tritania
website: https://github.com/tritania/Unicus

main: org.tritania.unicus.Unicus

commands:
  purge:
    description: Purges multihomes
    aliases: []
    usage: /<command> [playername]
  unpurge:
    description: removes the purges of multihomes
    aliases: []
    usage: /<command> [playername]
  plist:
    description: list all purged players
    aliases: []
    usage: /<command>
  pick:
    description: pick your new main home 
    aliases: []
    usage: /<command> [homename]
  transfer:
    description: transfer coins 
    aliases: []
    usage: /<command> [username] [amount]
  store:
    description: access to the adept store 
    aliases: []
    usage: /<command> [item] | [list]
  cadd:
    description: add a variable amount of coins 
    aliases: []
    usage: /<command> [username] [amount]
  cdel:
    description: remove a variable amount of coins 
    aliases: []
    usage: /<command> [username] [amount]
